#!/bin/sh

# regex to validate in commit msg

commit_regex='(EZT)-[0-9]{0,6}\w+|^Merge branch*'
error_msg="Aborting commit. Your commit message is missing a valid JIRA Ticket key and number. An example commit would be EZT-1234. Or 'Merge branch...'"

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
