#!/bin/bash

git=$(sh /etc/profile; which git)
branchName=$("${git}" rev-parse --abbrev-ref HEAD)

if [[ ${branchName} == "master" ]] || [[ ${branchName} == "develop" ]]; then
    echo "Checking out develop branch on each submodule"
    git submodule foreach --recursive git checkout develop
fi
